solidusio-contrib/solidus_related_products

app/views/spree/admin/products/_related_products.html.erb

- Use ` share-alt` icon to replace the missing `resize-small` one
Before:
After:

Use share-alt icon on admin instead of resize-small

---

app/views/spree/admin/products/_related_products_table.html.erb
app/views/spree/admin/products/related.html.erb
config/locales/de.yml

input-group seems to be broken in new solidus backend and the 'add' button was not displayed properly. So I change the structure a little bit and added german translation for the main navigation

some fixes for the new solidus 1.3 backend

---

app/views/spree/admin/products/_related_products_table.html.erb

Previously the link was resolving to products_path which maybe
undefined for users not using solidus frontend.
Replaces pull request #18

Namespaced product link to admin in _related_products_table.html.erb

---

config/initializers/spree.rb

Set active and keep the sub menu open when the related type tab under
products menu is selected.

Set active the related type tab if selected

---

.travis.yml

Those versions reached EOL and are no more supported

Do not run specs on travis for old versions

---

app/decorators/models/product/add_relation_interface_methods.rb
app/decorators/models/variant/add_relation_interface_methods.rb
spec/models/spree/product_spec.rb
spec/models/spree/variant_spec.rb

Avoid the solidus cache_key method override.

Rename cache_key interface methods to related_cache_key

---

app/overrides/add_related_product_admin_tabs.rb

I’ve been seeing Deface warnings in my logs about needing to add the original hash to this override. This PR adds the hash of the current `master` view from Solidus.

Add Deface original hash to override

---

app/views/spree/admin/relation_types/index.html.erb

This PR standardizes the styling of the backend button for the New Relation action.
Old:
New:

standardize backend button style for New Relation

---

app/views/spree/admin/relation_types/new.html.erb

This updates the breadcrumb style for relation_type/new to be more similar to other Solidus backend styling.
Solidus Backend:
Old:
New:

standardize breadcrumbs for New Relation

---

app/views/spree/admin/relation_types/edit.html.erb

This standardizes the admin breadcrumbs to be more similar to other Solidus backend views.
Old:
New:

Standardize breadcrumbs for relation_types/edit

---

app/views/spree/admin/products/related.html.erb

`button_link_to` helper is deprecated in Solidus (refs: https://github.com/solidusio/solidus/pull/2601).
So I replaced `button_link_to` with `link_to` helper.

Replace button_link_to helper with link_to helper

---

solidus_related_products.gemspec
spec/factories/relation_factory.rb
spec/factories/relation_type_factory.rb

This PR introduces the following changes to get a green Travis build once again:
* Lock SQLite3 to version 1.3 (see commit's description for details)
* Use dynamic attributes on factories

Fix Travis build

---

app/decorators/models/product/add_relation_methods.rb
spec/decorators/models/product/add_relation_methods_spec.rb

As described in #36 the `after_destroy` hook is no longer called, causing orphaned records on the destruction of a product

Use after_discard instead of after_destroy when available

---

app/assets/javascripts/spree/backend/create_relation.js.coffee
app/controllers/spree/admin/relations_controller.rb
app/controllers/spree/admin/variants/relations_controller.rb
app/controllers/spree/api/relations_controller.rb
app/controllers/spree/api/variants/relations_controller.rb
app/views/spree/admin/products/_related_products_table.html.erb
app/views/spree/admin/products/related.html.erb
app/views/spree/admin/variants/_related.html.erb
app/views/spree/admin/variants/_related_products_table.html.erb
db/migrate/20190513101010_add_description_to_spree_relations.rb
spec/controllers/spree/admin/relations_controller_spec.rb
spec/controllers/spree/admin/variants/relations_controller_spec.rb
spec/controllers/spree/api/relations_controller_spec.rb
spec/controllers/spree/api/variants/relations_controller_spec.rb
spec/features/spree/admin/product_relation_spec.rb
spec/features/spree/variant/product_relation_spec.rb
spec/models/spree/calculator/related_product_discount_spec.rb

This PR adds a new `Description` field in `Related Products` & `Related Variants` creation.
**Related Products**
**Related Variants**

Add 'description' in `Related Products` & `Related Variants` views

---

app/assets/javascripts/spree/backend/solidus_related_products.js

This PR changes how the assets are required by replacing the `require_tree .` in favor of more specific `require`s.
This allows to override single files from gem assets for `assets:precompile` because `require_tree` looks up files only in the directory of the current file and does not look across multiple load paths (e.g. `app/assets` or `vendor/assets`). So if the current file is `[gem]/app/assets/javascripts/gem_name/application.js`, `Sprockets#require_tree` will only look in `[gem]/app/assets/javascripts/gem_name/` for more files and will not use the other load paths like `[my_app]/app/assets/…`.

Change the require_tree directive with multiple requires

---

lib/solidus_related_products/factories.rb

Use traits to cover all possible `relation_type` and `relation` combinations. This will help the consumer developer to write specs.

Add factory traits to cover all relation combinations

---

app/assets/javascripts/spree/backend/related_to_autocomplete.js.coffee

The field to select a product in the related form allowed to choose from multiple products, but this was incorrect. Just one product can be selected for a relation.

Fix related product select form field

---

README.md
app/models/spree/relation.rb
app/models/spree/relation_type.rb
app/views/spree/admin/products/_related_products_table.html.erb
app/views/spree/admin/relation_types/_form.html.erb
app/views/spree/admin/relation_types/index.html.erb
config/locales/en.yml
db/migrate/20200402134239_add_bidirectional_to_spree_relation_type.rb
lib/solidus_related_products/factories.rb
spec/features/spree/admin/relation_types_spec.rb
spec/models/spree/relation_spec.rb
spec/models/spree/relation_type_spec.rb

This feature allows an admin user to create bidirectional relations. Notice that, for now, the bidirectional can be applied when `applies_from` and `applies_to` refer to the same model.
When a bidirectional relation is created, an inverse with the same `description` is added, in the same way, when one side of the relation is removed, also the other hand is destroyed.
The Bi-Directional aren't applied to the updates, so a change to the `description` or the `discount` won't affect the inverse relation.

Add Bi-Directional feature to the relations

---

app/views/spree/admin/relation_types/index.html.erb

This updates the admin breadcrumb to follow a parallel style to the current Option Types and Property Types breadcrumbs that are part of the default Solidus backend admin views.
Old Style:
New Style:

update backend admin breadcrumb

---

solidus_related_products.gemspec

At lesser versions, the test suite encounters an error and cannot run:
Failure/Error: Unable to find eval (eval at <anonymous> ((execjs) to
read failed line
ExecJS::ProgramError:
TypeError: Cannot read property 'version' of undefined
This seems related to the issue reported on Solidus: solidusio/solidus#4055. Adding `autoprefixer-rails` at the latest version side-steps the issue.

Force minimum version of `autoprefixer-rails`

---

lib/decorators/backend/controllers/solidus_related_products/admin/variants_controller/load_relation_types.rb

When the admin variants controller cannot successfully complete an
`#update` action, it re-renders the user back on the `#edit` action
view.
This causes `@relation_types` to be nil and makes the Deface template
that tries to load product relations error out on a
`@relation_types.empty?` block.
We can avoid this by just making sure this before action is performed on
`#update`, too.

Ensure `@relation_types` is assigned before #update

---

.gitignore
app/decorators/models/solidus_related_products/product/add_relation_methods.rb
app/decorators/models/solidus_related_products/variant/add_relation_methods.rb
app/views/spree/admin/products/_related_products.html.erb
lib/solidus_related_products/configuration.rb
solidus_related_products.gemspec
spec/models/spree/product_spec.rb
spec/spec_helper.rb

This PR adds `Spree::RelatedProductsConfiguration` class to allow for host app to pass in a `:no_conflict` configuration option.
If the `:no_conflict` configuration is set to `true`, then the method_missing defined relations in the product and variant decorators are disabled. This is to appease developers that think it is dangerous to allow end-users to define metaprogrammatic behavior in their application.
By default, `:no_conflict` is set to false so as not to break any existing apps.

Add :no_conflict configuration option

---

README.md

Resolves solidusio-contrib/solidus_related_products#89
Adds the suggestion in the README to install the gem directly from the Github repo.

Point gem in README to the github version

---

app/overrides/add_product_relation_admin_sub_menu_tab.rb

This adds a can can authorization check before adding the 'Relation Types' tab to the admin submenu.

Check admin auth before showing relation-type tab

---

lib/solidus_related_products/engine.rb

In Rails 7, you can't reference autoloaded constants in initializers (for good reason!) These get stored as strings and constantized anyway, so we can just pass in the string.

Fix constant reference in initializer
